/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapps;

import javax.swing.JOptionPane;
import mylibs.*;
import java.util.ArrayList;
import mylibs.Data;
/**
 *
 * @author DESKTOP
 */
public class addLot extends javax.swing.JFrame {
    
    Lot lot = new Lot();
    private ManageLotGUI mainGUI;
    private ArrayList<Lot> lots;

    /**
     * Creates new form addLot
     */
    public addLot() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
    }
    
    public addLot(ArrayList<Lot> lots, ManageLotGUI mainGUI) {
        this.mainGUI = mainGUI;
        this.lots = lots;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_lotNumber = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        tf_location = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf_blockNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_size = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_status = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_lotNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lotNumberActionPerformed(evt);
            }
        });

        tf_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_priceActionPerformed(evt);
            }
        });

        tf_location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_locationActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("ADD LOT");

        jLabel1.setText("Enter Block Number:");

        tf_blockNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_blockNumberActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Lot Number:");

        jLabel3.setText("Enter size (sqm):");

        jLabel4.setText("Enter status:");

        jLabel5.setText("Enter price:");

        tf_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sizeActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter location:");

        tf_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_statusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_size, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_blockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_lotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_status, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_location, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel9)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_blockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_lotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_lotNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lotNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lotNumberActionPerformed

    private void tf_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_priceActionPerformed

    private void tf_locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_locationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        // Get input from text fields
        String blockNumber = tf_blockNumber.getText().trim();
        String lotNumber = tf_lotNumber.getText().trim();
        String size = tf_size.getText().trim();
        String price = tf_price.getText().trim();
        String status = tf_status.getText().trim();
        String location = tf_location.getText().trim();

        // Validate inputs
        if (blockNumber.isEmpty() || lotNumber.isEmpty() || size.isEmpty() ||
            price.isEmpty() || status.isEmpty() || location.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;  // Stop further processing if any field is empty
        }

        // Validate numeric inputs
        int blockNum;
        int lotNum;
        double sizeInSqMeters;
        double priceValue;

        try {
            blockNum = Integer.parseInt(blockNumber);
            lotNum = Integer.parseInt(lotNumber);
            sizeInSqMeters = Double.parseDouble(size);
            priceValue = Double.parseDouble(price);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Block number, lot number, size, and price must be valid numbers.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;  // Stop if numeric conversion fails
        }
        
        
        if (!status.equalsIgnoreCase("Available") && !status.equalsIgnoreCase("Sold") && !status.equalsIgnoreCase("Reserved"))
            {
                JOptionPane.showMessageDialog(this, "Status must be either 'Available' or 'Sold' or 'Available'.", "Invalid Status", JOptionPane.WARNING_MESSAGE);
                return;
            }

        // Additional validation for size and price
        if (sizeInSqMeters <= 0) {
            JOptionPane.showMessageDialog(this, "Size must be a positive number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (priceValue <= 0) {
            JOptionPane.showMessageDialog(this, "Price must be a positive number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (Lot lot : Data.lots) {
            if (lot.getBlock() == blockNum && lot.getLotNumber() == lotNum) {
                JOptionPane.showMessageDialog(this, "A lot with the same block and lot number already exists.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;  // Stop if a duplicate is found
            }
        }

        // Create a new Lot object
        Lot newLot = new Lot(blockNum, lotNum, sizeInSqMeters, priceValue, status, location);
        
        // Add new lot to the collection
        Data.lots.add(newLot);
        mainGUI.sortLots();

        JOptionPane.showMessageDialog(this, "Lot information added!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        dispose();  // Close the dialog
        mainGUI.updateTable();  // Refresh the main GUI table

        } catch (Exception e) {
            // Show error message if something goes wrong
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_blockNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_blockNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_blockNumberActionPerformed

    private void tf_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sizeActionPerformed

    private void tf_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_statusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_blockNumber;
    private javax.swing.JTextField tf_location;
    private javax.swing.JTextField tf_lotNumber;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_size;
    private javax.swing.JTextField tf_status;
    // End of variables declaration//GEN-END:variables
}
