/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapps;

import javax.swing.JFrame;
import javax.swing.JLabel;
import mylibs.Lot;
import mylibs.Data;

/**
 *
 * @author DESKTOP
 */
public class CustomerUI extends javax.swing.JFrame {


    public CustomerUI(String username) {
        initComponents();
        setGreetingMessage(username);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        greetingUser = new javax.swing.JLabel();
        buylotbtn = new javax.swing.JButton();
        viewlotsbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        viewlotsbtn1 = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        reservebtn = new javax.swing.JButton();
        checkinvoicesbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        Panel.setMaximumSize(new java.awt.Dimension(1200, 700));
        Panel.setPreferredSize(new java.awt.Dimension(1200, 700));

        Welcome.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Welcome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        greetingUser.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        greetingUser.setText("Welcome to RESMS!");

        buylotbtn.setBackground(new java.awt.Color(204, 204, 255));
        buylotbtn.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        buylotbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buy_lot_logo.png"))); // NOI18N
        buylotbtn.setText("   Buy Lot");
        buylotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buylotbtnActionPerformed(evt);
            }
        });

        viewlotsbtn.setBackground(new java.awt.Color(204, 204, 255));
        viewlotsbtn.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        viewlotsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/view_lot_logo.png"))); // NOI18N
        viewlotsbtn.setText("   View Lots");
        viewlotsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlotsbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/profile_logo.png"))); // NOI18N

        viewlotsbtn1.setBackground(new java.awt.Color(204, 204, 255));
        viewlotsbtn1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        viewlotsbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/settings_logo.png"))); // NOI18N
        viewlotsbtn1.setText("   Settings");
        viewlotsbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewlotsbtn1ActionPerformed(evt);
            }
        });

        logoutbtn.setBackground(new java.awt.Color(204, 204, 255));
        logoutbtn.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logout_logo.png"))); // NOI18N
        logoutbtn.setText("  Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        reservebtn.setBackground(new java.awt.Color(204, 204, 255));
        reservebtn.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        reservebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rent_logo.png"))); // NOI18N
        reservebtn.setText("Reserve Lot");
        reservebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservebtnActionPerformed(evt);
            }
        });

        checkinvoicesbtn.setBackground(new java.awt.Color(204, 204, 255));
        checkinvoicesbtn.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        checkinvoicesbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/invoice.png"))); // NOI18N
        checkinvoicesbtn.setText("Invoices");
        checkinvoicesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinvoicesbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(buylotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(reservebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLayout.createSequentialGroup()
                                        .addComponent(viewlotsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(viewlotsbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkinvoicesbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(greetingUser)))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(greetingUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buylotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkinvoicesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewlotsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewlotsbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buylotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buylotbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BuyLot buy = new BuyLot(Welcome.getText());
        buy.setVisible(true);
    }//GEN-LAST:event_buylotbtnActionPerformed

    private void viewlotsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlotsbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        viewLots view = new viewLots(Welcome.getText());
        view.setVisible(true);
    }//GEN-LAST:event_viewlotsbtnActionPerformed

    private void viewlotsbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewlotsbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewlotsbtn1ActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        loginPanel login = new loginPanel();
        login.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void reservebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservebtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ReserveLot reserve = new ReserveLot(Welcome.getText());
        reserve.setVisible(true);
    }//GEN-LAST:event_reservebtnActionPerformed

    private void checkinvoicesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinvoicesbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        InvoiceUI invoice = new InvoiceUI(Welcome.getText());
        invoice.setVisible(true);
    }//GEN-LAST:event_checkinvoicesbtnActionPerformed

    private void setGreetingMessage(String username) {
        Welcome.setText(username); // Set the welcome message
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton buylotbtn;
    private javax.swing.JButton checkinvoicesbtn;
    private javax.swing.JLabel greetingUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton reservebtn;
    private javax.swing.JButton viewlotsbtn;
    private javax.swing.JButton viewlotsbtn1;
    // End of variables declaration//GEN-END:variables
}
