/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapps;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mylibs.Data;
import mylibs.Lot;

/**
 *
 * @author DESKTOP
 */
public class deleteLot extends javax.swing.JFrame {

    public ArrayList<Lot> lots;
    private ManageLotGUI mainGUI;
    
 
    
    public deleteLot(ArrayList<Lot> lots, ManageLotGUI mainGUI) 
    {
        this.lots = lots;
        this.mainGUI = mainGUI;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_blockNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_lotNumber = new javax.swing.JTextField();
        deleteLotBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_blockNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_blockNumberActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Lot Number:");

        tf_lotNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lotNumberActionPerformed(evt);
            }
        });

        deleteLotBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteLotBtn.setText("Delete Lot");
        deleteLotBtn.setAlignmentY(1.0F);
        deleteLotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLotBtnActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Delete Lot");

        jLabel1.setText("Enter Block Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_blockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_lotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(deleteLotBtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_blockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_lotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(deleteLotBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_blockNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_blockNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_blockNumberActionPerformed

    private void tf_lotNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lotNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lotNumberActionPerformed

    private void deleteLotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLotBtnActionPerformed
        try {
            String blockNumber = tf_blockNumber.getText().trim();
            String lotNumber = tf_lotNumber.getText().trim();

            if (blockNumber.isEmpty() || lotNumber.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;  // Stop if any field is empty
            }

            int blockNum = Integer.parseInt(blockNumber);
            int lotNum = Integer.parseInt(lotNumber);

           Lot lotToDelete = null;
            for (Lot lot : Data.lots) {
                if (lot.getBlock() == blockNum && lot.getLotNumber() == lotNum) {
                    lotToDelete = lot;
                    break;
                }
            }

            if (lotToDelete != null) {
                // Remove the lot from the list
                Data.lots.remove(lotToDelete);
                JOptionPane.showMessageDialog(this, "Lot deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                
                // remove corresponding Buy objects from Data.buys
                Data.buys.removeIf(buy -> buy.getBlockNumber() == blockNum && buy.getLotNumber() == lotNum);
                Data.reserves.removeIf(buy -> buy.getBlockNumber() == blockNum && buy.getLotNumber() == lotNum);
            
            // Optional: Notify the user about the removal of Buy objects
                JOptionPane.showMessageDialog(this, "Corresponding purchases deleted as well!", "Success", JOptionPane.INFORMATION_MESSAGE);
                
                mainGUI.sortLots();
                mainGUI.updateTable(); // Refresh the table in the main GUI
                dispose(); // Close the form
            }
            else 
            {
                // Lot not found
                JOptionPane.showMessageDialog(this, "Lot not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteLotBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteLotBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_blockNumber;
    private javax.swing.JTextField tf_lotNumber;
    // End of variables declaration//GEN-END:variables
}
