/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapps;

import javax.swing.JOptionPane;
import mylibs.Lot;
import mylibs.Data;
import mylibs.Buy;

/**
 *
 * @author DESKTOP
 */
public class LotDetails extends javax.swing.JFrame {

    private Lot selectedLot;
    private String user;
    
    public LotDetails(Lot lot, String username) {
        this.user = username;
        this.selectedLot = lot;
        
        initComponents();
        displayLotDetails();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        greetingUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        showblock = new javax.swing.JLabel();
        showlocation = new javax.swing.JLabel();
        showsize = new javax.swing.JLabel();
        showstatus = new javax.swing.JLabel();
        showprice = new javax.swing.JLabel();
        showlot = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        messageField = new javax.swing.JTextField();
        contactagentbutton = new javax.swing.JToggleButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        greetingUser.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        greetingUser.setForeground(new java.awt.Color(255, 255, 255));
        greetingUser.setText("Lot Details");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/lotdet_logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Size:");

        adada.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        adada.setForeground(new java.awt.Color(255, 255, 255));
        adada.setText("Block Number:");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lot Number:");

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price:");

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status:");

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location:");

        showblock.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        showblock.setForeground(new java.awt.Color(255, 255, 255));
        showblock.setText("<<block number>>");

        showlocation.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        showlocation.setForeground(new java.awt.Color(255, 255, 255));
        showlocation.setText("<<location>>");

        showsize.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        showsize.setForeground(new java.awt.Color(255, 255, 255));
        showsize.setText("<<size>>");

        showstatus.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        showstatus.setForeground(new java.awt.Color(255, 255, 255));
        showstatus.setText("<<status>>");

        showprice.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        showprice.setForeground(new java.awt.Color(255, 255, 255));
        showprice.setText("<<price>");

        showlot.setFont(new java.awt.Font("Bodoni MT", 0, 24)); // NOI18N
        showlot.setForeground(new java.awt.Color(255, 255, 255));
        showlot.setText("<<lot number>>");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel8.setText("Name");

        nameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel9.setText("Contact Number");

        contactField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel10.setText("Email");

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel11.setText("Message");

        messageField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        messageField.setText("I am Interested in this lot.");

        contactagentbutton.setBackground(new java.awt.Color(102, 102, 255));
        contactagentbutton.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        contactagentbutton.setForeground(new java.awt.Color(255, 255, 255));
        contactagentbutton.setText("Contact Agent");
        contactagentbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contactagentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactagentbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField)
                    .addComponent(contactField)
                    .addComponent(emailField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(messageField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contactagentbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(contactagentbutton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        backbtn.setBackground(new java.awt.Color(204, 204, 255));
        backbtn.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logout_logo.png"))); // NOI18N
        backbtn.setText(" Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adada)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showlot)
                            .addComponent(showblock)
                            .addComponent(showsize)
                            .addComponent(showprice)
                            .addComponent(showstatus)
                            .addComponent(showlocation)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(greetingUser, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(greetingUser)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showblock)
                    .addComponent(adada))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(showlot))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(showsize))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(showprice))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(showstatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(showlocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CustomerUI customerUI = new CustomerUI(user); // Pass the welcome text back to CustomerUI
        customerUI.setVisible(true);

    }//GEN-LAST:event_backbtnActionPerformed

    private void contactagentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactagentbuttonActionPerformed
        // TODO add your handling code here:
        try {
        // Generate a new BuyID
        String LatestBuyID = Data.checkLatestBuy();
        String BuyID = "B" + (Integer.parseInt(LatestBuyID.substring(1)) + 1);  // Generates a new BuyID
        
        // Fetch user input from fields
        String name = nameField.getText().trim();
        String contact = contactField.getText().trim();
        String email = emailField.getText().trim();
        String paymentMethod = null;  // Payment method can be set later
        String status = "Pending";
        String message = messageField.getText().trim();    
        int blocknum = selectedLot.getBlock();
        int lotnum = selectedLot.getLotNumber();  
        String username = user;  // Fetch the username (assuming it's displayed in the UI via Welcome label)

        // Validation: Ensure all required fields are filled
        if (name.isEmpty() || contact.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
            return;
        }

        // Validation: Check for valid email format
        if (!email.contains("@") || !email.contains(".")) {
            JOptionPane.showMessageDialog(null, "Invalid Email!", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create a Buy object using the builder pattern (Assuming BuyBuilder exists)
        Buy buydetails = new Buy.Builder()
                            .setBuyID(BuyID)
                            .setName(name)
                            .setContact(contact)
                            .setEmail(email)
                            .setPaymentMethod(paymentMethod)
                            .setStatus(status)
                            .setMessage(message)
                            .setBlockNumber(blocknum)
                            .setLotNumber(lotnum)
                            .setUsername(username)  // Pass the username
                            .build();
        
        // Add the Buy object to the Data.buys ArrayList
        Data.buys.add(buydetails);

        // Update lot status to 'Pending' in the lots ArrayList
        for (Lot lot : Data.lots) {
            if (lot.getBlock() == blocknum && lot.getLotNumber() == lotnum) {
                lot.setStatus("Pending");  // Update the lot status to Pending
                break;  // Exit loop once the lot is found and updated
            }
        }

            JOptionPane.showMessageDialog(null, "Your request has been placed, please wait for admin approval to proceed with payment.");

            this.dispose();  
            CustomerUI custom = new CustomerUI(username);
            custom.setVisible(true); 

        } catch (NumberFormatException e) {
            // Handle potential issues with BuyID parsing
            JOptionPane.showMessageDialog(null, "Error generating BuyID: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Catch any other potential exceptions
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
             
    }//GEN-LAST:event_contactagentbuttonActionPerformed

    
    private void displayLotDetails()
    {
        showblock.setText(String.valueOf(selectedLot.getBlock()));
        showlot.setText(String.valueOf(selectedLot.getLotNumber()));
        showsize.setText(String.valueOf(selectedLot.getSize()) + " sqm");
        showprice.setText( "Php "+String.valueOf(selectedLot.getPrice()));
        showstatus.setText(selectedLot.getStatus());
        showlocation.setText(selectedLot.getLocation());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adada;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField contactField;
    private javax.swing.JToggleButton contactagentbutton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel greetingUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField messageField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel showblock;
    private javax.swing.JLabel showlocation;
    private javax.swing.JLabel showlot;
    private javax.swing.JLabel showprice;
    private javax.swing.JLabel showsize;
    private javax.swing.JLabel showstatus;
    // End of variables declaration//GEN-END:variables
}
