/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapps;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.swing.JOptionPane;
import mylibs.Buy;
import mylibs.Data;
import mylibs.Invoice;
import mylibs.Lot;

/**
 *
 * @author DESKTOP
 */
public class ModifyPurchaseGUI extends javax.swing.JFrame {

    private Buy selectedBuy;

    public ModifyPurchaseGUI(Buy buy) {
        this.selectedBuy = buy;
        initComponents();
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
        displayPurchaseDetails();
        getLotDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showemail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showcontact = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        showblock = new javax.swing.JLabel();
        showlot = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        showsize = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        showprice = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        showlocation = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        showid = new javax.swing.JLabel();
        showstatus = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        showpayment = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        showmessage = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        marksoldbtn = new javax.swing.JButton();
        backtopendingbtn = new javax.swing.JButton();
        sendinvoicebtn = new javax.swing.JButton();
        canceltransactionbtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        managependingsnav = new javax.swing.JLabel();
        generatereportnav = new javax.swing.JLabel();
        managelotnav = new javax.swing.JLabel();
        managecustomersnav = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        backbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Customer Information");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(67, 24, 229, 29);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/profile_logo.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(12, 13, 48, 48);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 79, 50, 21);

        showname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showname.setText("<<name>>");
        jPanel1.add(showname);
        showname.setBounds(106, 79, 260, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 107, 50, 21);

        showemail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showemail.setText("<<email>>");
        jPanel1.add(showemail);
        showemail.setBounds(106, 107, 260, 21);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Contact:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 135, 67, 21);

        showcontact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showcontact.setText("<<contact>>");
        jPanel1.add(showcontact);
        showcontact.setBounds(106, 135, 270, 21);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buy_lot_logo.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(12, 13, 48, 48);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Lot Information");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(72, 23, 165, 29);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel16.setText("Block Number:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 70, 152, 29);

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel17.setText("Lot Number:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 110, 127, 29);

        showblock.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        showblock.setText("1");
        jPanel2.add(showblock);
        showblock.setBounds(200, 70, 100, 26);

        showlot.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        showlot.setText("1");
        jPanel2.add(showlot);
        showlot.setBounds(200, 110, 100, 26);

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel19.setText("Size(sqm):");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(340, 110, 108, 29);

        showsize.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        showsize.setText("<<size>>");
        jPanel2.add(showsize);
        showsize.setBounds(470, 110, 140, 30);

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel20.setText("Price:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(340, 70, 59, 29);

        showprice.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        showprice.setText("<<price>>");
        jPanel2.add(showprice);
        showprice.setBounds(470, 70, 150, 26);

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel21.setText("Location:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(620, 70, 95, 29);

        showlocation.setFont(new java.awt.Font("Serif", 0, 22)); // NOI18N
        showlocation.setText("<<location>>");
        jPanel2.add(showlocation);
        showlocation.setBounds(730, 70, 270, 26);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(573, 175));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/rent_logo.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Purchase Information");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Purchase ID:");

        showid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showid.setText("<<buyid>>");

        showstatus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showstatus.setText("<<status>>");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Payment Method:");

        showpayment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showpayment.setText("<<payment>>");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Message:");

        showmessage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        showmessage.setText("<<message>>");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Status:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showstatus)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showid)
                                    .addComponent(showpayment))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showmessage)
                                    .addComponent(jLabel18)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(showid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(showpayment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(showstatus)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showmessage)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        marksoldbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        marksoldbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/sold.png"))); // NOI18N
        marksoldbtn.setText("Mark as Sold");
        marksoldbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksoldbtnActionPerformed(evt);
            }
        });

        backtopendingbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backtopendingbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/pending.png"))); // NOI18N
        backtopendingbtn.setText("Back to Pending");
        backtopendingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtopendingbtnActionPerformed(evt);
            }
        });

        sendinvoicebtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sendinvoicebtn.setForeground(new java.awt.Color(255, 51, 51));
        sendinvoicebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/invoice.png"))); // NOI18N
        sendinvoicebtn.setText("  Send Invoice");
        sendinvoicebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendinvoicebtnActionPerformed(evt);
            }
        });

        canceltransactionbtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        canceltransactionbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/cancel.png"))); // NOI18N
        canceltransactionbtn.setText("Cancel Transaction");
        canceltransactionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceltransactionbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backtopendingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(marksoldbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(canceltransactionbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addComponent(sendinvoicebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marksoldbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canceltransactionbtn))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendinvoicebtn)
                    .addComponent(backtopendingbtn))
                .addGap(24, 24, 24))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(null);

        managependingsnav.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        managependingsnav.setText("Manage Purchases");
        managependingsnav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managependingsnavMouseClicked(evt);
            }
        });
        jPanel5.add(managependingsnav);
        managependingsnav.setBounds(10, 20, 230, 30);

        generatereportnav.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        generatereportnav.setText("Generate Report");
        generatereportnav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generatereportnavMouseClicked(evt);
            }
        });
        jPanel5.add(generatereportnav);
        generatereportnav.setBounds(270, 20, 200, 32);

        managelotnav.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        managelotnav.setText("Manage Lots");
        managelotnav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managelotnavMouseClicked(evt);
            }
        });
        jPanel5.add(managelotnav);
        managelotnav.setBounds(520, 20, 160, 32);

        managecustomersnav.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        managecustomersnav.setText("Manage Users");
        managecustomersnav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managecustomersnavMouseClicked(evt);
            }
        });
        jPanel5.add(managecustomersnav);
        managecustomersnav.setBounds(710, 20, 240, 32);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(690, 10, 10, 50);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(250, 10, 10, 50);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(490, 10, 10, 50);

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/back.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel5.add(backbtn);
        backbtn.setBounds(1130, 10, 48, 48);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marksoldbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksoldbtnActionPerformed
        // TODO add your handling code here:
        int blocknum = selectedBuy.getBlockNumber();
        int lotNum = selectedBuy.getLotNumber();
        for (Lot lot : Data.lots) 
        {
            if (lot.getBlock() == blocknum && lot.getLotNumber() == lotNum) {
                lot.setStatus("Sold");
                selectedBuy = selectedBuy.toBuilder()
                        .setStatus("Sold")
                        .build();
                
                for (int i = 0; i < Data.buys.size(); i++) 
                {
                    if (Data.buys.get(i).getBuyID().equals(selectedBuy.getBuyID())) 
                    {
                        Data.buys.set(i, selectedBuy);
                        break;
                    }
                }
                
                JOptionPane.showMessageDialog(this, "Lot mark as Sold and Transaction Completed!", "Success", JOptionPane.INFORMATION_MESSAGE);
                displayPurchaseDetails();
                return;  // Exit loop once the lot is found
            }
        }
        JOptionPane.showMessageDialog(this, "Error: Lot not found", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_marksoldbtnActionPerformed

    private void backtopendingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtopendingbtnActionPerformed
        // TODO add your handling code here:
        int blocknum = selectedBuy.getBlockNumber();
        int lotNum = selectedBuy.getLotNumber();
        for (Lot lot : Data.lots) 
        {
            if (lot.getBlock() == blocknum && lot.getLotNumber() == lotNum) {

                // Example: Displaying or using lot details
     
                lot.setStatus("Pending");
                selectedBuy = selectedBuy.toBuilder()
                        .setStatus("Pending")
                        .build();
                
                for (int i = 0; i < Data.buys.size(); i++) {
                if (Data.buys.get(i).getBuyID().equals(selectedBuy.getBuyID())) {
                    Data.buys.set(i, selectedBuy);  // Update the existing Buy object
                    break;
                }
                }
                
                JOptionPane.showMessageDialog(this, "Lot mark as Pending", "Success", JOptionPane.INFORMATION_MESSAGE);
                displayPurchaseDetails();
                return;  // Exit loop once the lot is found
            }
        }
        JOptionPane.showMessageDialog(this, "Error: Lot not found", "Error", JOptionPane.ERROR_MESSAGE);
       
    }//GEN-LAST:event_backtopendingbtnActionPerformed

    private void sendinvoicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendinvoicebtnActionPerformed
        // TODO add your handling code here:
        String username = selectedBuy.getUsername();
        String latestDocumentID = Data.checkLatestDocumentID();
        String documentID = "D" + (Integer.parseInt(latestDocumentID.substring(1)) + 1);
        String date;
        while (true) {
            date = JOptionPane.showInputDialog(this, "Enter the invoice date (e.g., YYYY-MM-DD):", "Date Input", JOptionPane.PLAIN_MESSAGE); 

            // Check for null or empty input
            if (date == null || date.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Date is required to create an invoice.", "Error", JOptionPane.ERROR_MESSAGE);
                return;  // Stop if the date is not provided
            }

            // Validate the date format
            if (isValidDate(date)) {
                break; // Exit the loop if the date is valid
            } else {
                JOptionPane.showMessageDialog(this, "Invalid date format. Please enter the date in YYYY-MM-DD format.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        String name = selectedBuy.getName();
        String contact = selectedBuy.getContact();
        String email = selectedBuy.getEmail();
        
        if (date == null || date.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Date is required to create an invoice.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  // Stop if the date is not provided
        }
        
        for (Invoice invoice : Data.invoices) {
            if (invoice.getUsername().equals(username) &&
                invoice.getBlockNumber() == selectedBuy.getBlockNumber() &&
                invoice.getLotNumber() == selectedBuy.getLotNumber()) {
                JOptionPane.showMessageDialog(this, "An invoice has already been sent for this purchase.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Stop if an invoice already exists
            }
        }
        
        int blocknum = selectedBuy.getBlockNumber();
        int lotNum = selectedBuy.getLotNumber();
        
        double totalAmount = 0;
        String location = "";
        double size = 0;
        for (Lot lot : Data.lots) 
        {
            if (lot.getBlock() == blocknum && lot.getLotNumber() == lotNum) 
            {
                totalAmount = lot.getPrice();
                location = lot.getLocation();
                size = lot.getSize();
            }
        }
        
        Invoice invoice = new Invoice.Builder()
            .setDocumentID(documentID)
            .setUsername(username)
            .setTotalAmount(totalAmount)
            .setBlockNumber(blocknum)
            .setLotNumber(lotNum)
            .setLocation(location)
            .setDate(date)
            .setSize(size)
            .setName(name)
            .setEmail(email)
            .setContactNumber(contact)
        
            .build();
        
         Data.invoices.add(invoice);           
        
        JOptionPane.showMessageDialog(this, "Invoice sent successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_sendinvoicebtnActionPerformed

    private boolean isValidDate(String date) {
        String datePattern = "\\d{4}-\\d{2}-\\d{2}";
        if (!date.matches(datePattern)) {
            return false; // If the format is incorrect, return false
        }

        // Now, check if it's a valid date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false); // Set lenient to false to strictly validate the date

        try {
            Date parsedDate = sdf.parse(date);
            return true; // Date is valid
        } catch (ParseException e) {
            return false; // Date is not valid
        }
    }
    
    private void canceltransactionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceltransactionbtnActionPerformed
        // TODO add your handling code here:
        int blocknum = selectedBuy.getBlockNumber();
        int lotNum = selectedBuy.getLotNumber();
        for (Lot lot : Data.lots) 
        {
            if (lot.getBlock() == blocknum && lot.getLotNumber() == lotNum) 
            {
                // Example: Displaying or using lot details
     
                lot.setStatus("Available");
                
                for (int i = 0; i < Data.buys.size(); i++) 
                {
                    if (Data.buys.get(i).getBuyID().equals(selectedBuy.getBuyID())) 
                    {
                        Data.buys.remove(i);
                        break;
                    }
                }
                JOptionPane.showMessageDialog(this, "Transaction Cancelled", "Success", JOptionPane.INFORMATION_MESSAGE);
                displayPurchaseDetails();
                return;  // Exit loop once the lot is found
            }
        }
        JOptionPane.showMessageDialog(this, "Error: Lot not found", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_canceltransactionbtnActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ManagePurchasesGUI managepurchases = new ManagePurchasesGUI();
        managepurchases.setVisible(true);
    }//GEN-LAST:event_backbtnMouseClicked

    private void managecustomersnavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managecustomersnavMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ManageCustomersGUI managecustomers = new ManageCustomersGUI();
        managecustomers.setVisible(true);
    }//GEN-LAST:event_managecustomersnavMouseClicked

    private void managelotnavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managelotnavMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ManageLotGUI managelot = new ManageLotGUI();
        managelot.setVisible(true);
    }//GEN-LAST:event_managelotnavMouseClicked

    private void generatereportnavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generatereportnavMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ManageReportGUI manage = new ManageReportGUI();
        manage.setVisible(true);
    }//GEN-LAST:event_generatereportnavMouseClicked

    private void managependingsnavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managependingsnavMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        ManagePurchasesGUI managepurchases = new ManagePurchasesGUI();
        managepurchases.setVisible(true);
    }//GEN-LAST:event_managependingsnavMouseClicked

    public void getLotDetails()
    {
        int blocknum = selectedBuy.getBlockNumber();
        int lotNum = selectedBuy.getLotNumber();
        
        for (Lot lot : Data.lots) 
        {
            if (lot.getBlock() == blocknum && lot.getLotNumber() == lotNum) {

                // Example: Displaying or using lot details
                double size = lot.getSize();
                double price = lot.getPrice();
                String lotStatus = lot.getStatus();                
                String location = lot.getLocation();
                showsize.setText(String.valueOf(size));
                showprice.setText(String.valueOf(price));
                showlocation.setText(location);

                return;  // Exit loop once the lot is found
            }
        }
            
    }
    
    private void displayPurchaseDetails()
    {
        showid.setText(String.valueOf(selectedBuy.getBuyID()));
        showname.setText(String.valueOf(selectedBuy.getName()));
        showemail.setText(String.valueOf(selectedBuy.getEmail()));
        showcontact.setText(String.valueOf(selectedBuy.getContact()));
        showstatus.setText(String.valueOf(selectedBuy.getStatus()));
        showpayment.setText(String.valueOf(selectedBuy.getPaymentMethod()));
        showmessage.setText(String.valueOf(selectedBuy.getMessage()));
        showblock.setText(String.valueOf(selectedBuy.getBlockNumber()));
        showlot.setText(String.valueOf(selectedBuy.getLotNumber()));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbtn;
    private javax.swing.JButton backtopendingbtn;
    private javax.swing.JButton canceltransactionbtn;
    private javax.swing.JLabel generatereportnav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel managecustomersnav;
    private javax.swing.JLabel managelotnav;
    private javax.swing.JLabel managependingsnav;
    private javax.swing.JButton marksoldbtn;
    private javax.swing.JButton sendinvoicebtn;
    private javax.swing.JLabel showblock;
    private javax.swing.JLabel showcontact;
    private javax.swing.JLabel showemail;
    private javax.swing.JLabel showid;
    private javax.swing.JLabel showlocation;
    private javax.swing.JLabel showlot;
    private javax.swing.JLabel showmessage;
    private javax.swing.JLabel showname;
    private javax.swing.JLabel showpayment;
    private javax.swing.JLabel showprice;
    private javax.swing.JLabel showsize;
    private javax.swing.JLabel showstatus;
    // End of variables declaration//GEN-END:variables
}
