/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myapps;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import mylibs.Buy;
import mylibs.Data;
import mylibs.Lot;
import mylibs.Reserve;

/**
 *
 * @author DESKTOP
 */
public class updateLot extends javax.swing.JFrame {

    public ArrayList<Lot> lots;
    private ManageLotGUI mainGUI;
    
    public updateLot() {
        this.lots = lots;
        this.mainGUI = mainGUI;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
    }
    
    public updateLot(ArrayList<Lot> lots, ManageLotGUI mainGUI) 
    {
        this.lots = lots;
        this.mainGUI = mainGUI;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setLocationRelativeTo(null); // Center the form on the screen
        pack(); // Pack the components to their preferred sizes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_blockNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_newSize = new javax.swing.JTextField();
        tf_lotNumber = new javax.swing.JTextField();
        updateStatusBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_newLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_newPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_newStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tf_blockNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_blockNumberActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Lot Number:");

        jLabel3.setText("New Size:");

        tf_newSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_newSizeActionPerformed(evt);
            }
        });

        tf_lotNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lotNumberActionPerformed(evt);
            }
        });

        updateStatusBtn.setBackground(new java.awt.Color(153, 255, 153));
        updateStatusBtn.setText("Update Lot");
        updateStatusBtn.setAlignmentY(1.0F);
        updateStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStatusBtnActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Update Status");

        jLabel1.setText("Enter Block Number:");

        jLabel4.setText("New Price:");

        tf_newLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_newLocationActionPerformed(evt);
            }
        });

        jLabel5.setText("New Status:");

        tf_newPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_newPriceActionPerformed(evt);
            }
        });

        jLabel6.setText("New Location:");

        tf_newStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_newStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(updateStatusBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_newPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_newSize, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_blockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_lotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_newStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_newLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_blockNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_lotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_newSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_newPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_newStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_newLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(updateStatusBtn)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_blockNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_blockNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_blockNumberActionPerformed

    private void tf_newSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_newSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_newSizeActionPerformed

    private void tf_lotNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lotNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lotNumberActionPerformed

    private void updateStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatusBtnActionPerformed
        try {
            String blockNumberstr = tf_blockNumber.getText().trim();
            String lotNumberstr = tf_lotNumber.getText().trim();
            String newSizestr = tf_newSize.getText().trim();
            String newPricestr = tf_newPrice.getText() .trim();
            String newStatus = tf_newLocation.getText().trim();
            String newLocation = tf_newLocation.getText().trim();
            
            if(blockNumberstr.isEmpty() || lotNumberstr.isEmpty() || newSizestr.isEmpty() || newPricestr.isEmpty() || newStatus.isEmpty() || newLocation.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "All fields must be filled out.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int blockNumber = Integer.parseInt(blockNumberstr);
            int lotNumber = Integer.parseInt(lotNumberstr);
            double size = Double.parseDouble(newSizestr);
            double price = Double.parseDouble(newPricestr);
            
            boolean lotfound = false;
            for (Lot lot : lots) {
                if (lot.getBlock() == blockNumber && lot.getLotNumber() == lotNumber) { // Use == for int comparison
                    lotfound = true;
                    break;
                }
            }

            if (!lotfound) {
                    JOptionPane.showMessageDialog(this, "No lot found with the provided block and lot number.", "Warning", JOptionPane.WARNING_MESSAGE);
                }

            if (!newStatus.equalsIgnoreCase("Available") && !newStatus.equalsIgnoreCase("Sold") && !newStatus.equalsIgnoreCase("Reserved"))
            {
                JOptionPane.showMessageDialog(this, "Status must be either 'Available' or 'Sold' or 'Reserved'.", "Invalid Status", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            
            boolean found = false;
        for (Lot lot : Data.lots) {
            if (lot.getBlock() == blockNumber && lot.getLotNumber() == lotNumber) {
                lot.setSize(size);
                lot.setPrice(price);  
                lot.setStatus(newStatus);
                lot.setLocation(newLocation);

                // Update corresponding Buy objects
                for (int i = 0; i < Data.buys.size(); i++) {
                    Buy buy = Data.buys.get(i);
                    if (buy.getBlockNumber() == blockNumber && buy.getLotNumber() == lotNumber) {
                        Buy updatedBuy = buy.toBuilder() 
                            .setStatus(newStatus) 
                            .build();

                        // Replace the existing Buy object in the ArrayList
                        Data.buys.set(i, updatedBuy);
                    }
                }
                
                for (int i = 0; i < Data.reserves.size(); i++) {
                    Reserve reserve = Data.reserves.get(i);
                    if (reserve.getBlockNumber() == blockNumber && reserve.getLotNumber() == lotNumber) {
                        Reserve updatedReserve = reserve.toBuilder() 
                            .setStatus(newStatus) 
                            .build();

                        // Replace the existing Buy object in the ArrayList
                        Data.reserves.set(i, updatedReserve);
                    }
                }

                found = true;
                JOptionPane.showMessageDialog(this, "Lot details updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                mainGUI.sortLots();
                mainGUI.updateTable();  // Refresh the table in the main GUI
                dispose();  // Close the form
                break;
            }
                }

        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateStatusBtnActionPerformed

    private void tf_newLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_newLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_newLocationActionPerformed

    private void tf_newPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_newPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_newPriceActionPerformed

    private void tf_newStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_newStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_newStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_blockNumber;
    private javax.swing.JTextField tf_lotNumber;
    private javax.swing.JTextField tf_newLocation;
    private javax.swing.JTextField tf_newPrice;
    private javax.swing.JTextField tf_newSize;
    private javax.swing.JTextField tf_newStatus;
    private javax.swing.JButton updateStatusBtn;
    // End of variables declaration//GEN-END:variables
}
